# RBAC for Grafana to access Prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: maas-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-prometheus-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- nonResourceURLs: ["/metrics", "/federate", "/api/*"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-prometheus-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-prometheus-reader
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: maas-observability
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: maas-observability
  annotations:
    kubernetes.io/service-account.name: grafana-sa
type: kubernetes.io/service-account-token