---
apiVersion: v1
kind: Namespace
metadata:
  name: maas-observability
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: maas-observability
  labels:
    app: grafana
spec:
  route:
    spec:
      host: grafana.apps.maas2.octo-emerging.redhataicoe.com
      to:
        kind: Service
        name: grafana-service
      port:
        targetPort: grafana-http
  deployment:
    spec:
      replicas: 1
  config:
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "true"
    log:
      mode: console
    security:
      admin_password: secret
      admin_user: root